### ISSUE TITLE
80% of the entire project's code shall be covered by unit tests (for Backend)

### ISSUE THREAD

**Issue by ehharvey** [CSCN73030-projectv-group9/Attendance#77]

**Comment by Amanuel-Negussie** [comment]
Will work on backend uT.

**Comment by ehharvey** [comment]
Making a separate new issue for Frontend tests

**Comment by Amanuel-Negussie** [comment]
Hey @ehharvey , I wanted to know how to create mocks that have a return value, and how to validate that? So far I see that functions being called once are a way we test (ex. is_dir_mock.assert_called_once()), but I'm trying to create a mock of an attendance where I can create the return value of a function and assert that not only it's been called but I guess that the value is as expected. This matters for update: because it shows the difference between original and updated attendance.
![image](https://user-images.githubusercontent.com/74369791/203420910-768f6497-5a25-4783-a61c-3b54997869e9.png)


Also an update: Locally, the coverage for backend is at 62%.
![image](https://user-images.githubusercontent.com/74369791/203421042-545ae609-b373-4268-b0fd-4b8311ced5b6.png)

**Comment by Amanuel-Negussie** [comment]
Setup/Teardown with Pytest Fixtures
https://stackoverflow.com/questions/22627659/run-code-before-and-after-each-test-in-py-test 
https://docs.pytest.org/en/6.2.x/fixture.html
There is a concept of pytest fixtures that we may use, that will help with setup and teardown, to remove the wordiness of each test case.
